name: Bug Report
description: Report a bug in the Plexus C SDK
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - ESP32 (ESP-IDF)
        - ESP32 (Arduino)
        - ESP8266 (Arduino)
        - STM32
        - Other
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: Output of plexus_version() or version in library.json
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: framework-version
    attributes:
      label: Framework Version
      description: e.g., ESP-IDF v5.1, Arduino ESP32 2.0.14, STM32CubeF4 1.28.0
      placeholder: "ESP-IDF v5.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Minimal code to reproduce the issue
      render: c
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration Flags
      description: Any non-default PLEXUS_* defines
      placeholder: |
        #define PLEXUS_MAX_METRICS 8
        #define PLEXUS_ENABLE_TAGS 0
      render: c

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs
      description: Output with PLEXUS_DEBUG=1 enabled
      render: text
