name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this feature solve? What are you trying to do?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work? Include example API if applicable.
      render: c

  - type: checkboxes
    id: platforms
    attributes:
      label: Affected Platforms
      description: Which platforms would benefit from this feature?
      options:
        - label: ESP32 (ESP-IDF)
        - label: ESP32 (Arduino)
        - label: ESP8266 (Arduino)
        - label: STM32
        - label: All platforms

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to your project?
      options:
        - Nice to have
        - Important — working around it today
        - Critical — blocking my project
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this feature
